blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
    path('blog/',views.blog,name='blog'),
    path('contact/',views.contact,name='contact'),
    path('contact_view/',views.contact_view,name='contact_view'),
    path('blog/<int:id>/',views.blog_detail,name='blog-detail')
]

info/urls.py
from django.urls import path
from . import views
app_name='info'
urlpatterns = [
   path('',views.home,name='home'),
   path('about/',views.about,name='about'),
   path('service/',views.service,name='service'),
   path('about/<int:id>/',views.about_view,name='about-detail')
]

new_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('info.urls')),
    path('',include('blog.urls')),
    path('',include('user.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name="user"
urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('register/',views.register_view,name='register'),
    path('logout_view/',views.logout_view,name='logout'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Author(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    bio=models.CharField(max_length=40)

    def __str__(self):
        return self.user.username
    
class Tag(models.Model):
    title=models.CharField(max_length=25)

    def __str__(self):
        return self.title

class Blog(models.Model):
    title=models.CharField()
    description=models.CharField()
    content=models.CharField()
    value=models.BooleanField(default=True)
    view_count=models.IntegerField()
    image=models.ImageField(null=True,blank=True)
    create_time=models.DateField(auto_now_add=True)
    author=models.ForeignKey(Author,on_delete=models.SET_NULL,blank=True,null=True)
    tag=models.ManyToManyField(Tag)

    def __str__(self):
        return self.title
    


    

class Contact(models.Model):
    name=models.CharField()
    phone=models.CharField()
    time=models.CharField()
    email=models.EmailField()
    massage=models.TextField()
    date=models.CharField()
    message=models.TextField()

    def __str__(self):
        return self.name

info/models.py
from django.db import models

# Create your models here.
class About(models.Model):
    title=models.CharField()
    description=models.CharField()
    image=models.ImageField(null=True,blank=True)
    count_view=models.IntegerField()
    show=models.BooleanField(default=True,)
    create_time=models.DateField( auto_now_add=True)

    def __str__(self):
        return self.title

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.models import User

import re



username_compiler=re.compile(r'^\w{5,}$')

class RegisterForm(forms.Form):
    first_name=forms.CharField()
    last_name=forms.CharField()
    username=forms.CharField()
    email=forms.EmailField()
    password=forms.CharField(widget=forms.PasswordInput)
    password_again=forms.CharField(widget=forms.PasswordInput)

    
    def save(self):
        first_name=self.cleaned_data.get('first_name')
        last_name=self.cleaned_data.get('last_name')
        username=self.cleaned_data.get('username')
        email=self.cleaned_data.get('email')
        password=self.cleaned_data.get('password')
        user=User.objects.create_user(
            username=username,
            first_name=first_name,
            last_name=last_name,
            email=email,
            password=password
        )
        return user
    
    def clean_username(self):
        username=self.cleaned_data.get('username')
        if not username_compiler.match(username):
            raise forms.ValidationError('Istifadeci adi uygun deyil')
        elif User.objects.filter(username=username).exists():
            raise forms.ValidationError('Istifadeci adi bir defe daxil edilib')
        
        return username
    
    def clean_email(self):
        email=self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('email artiq bir defe istifade olunub')
        
        return email
    
    def clean(self):
        super().clean()
        password=self.cleaned_data.get('password')
        password_again=self.cleaned_data.get('password_again')
        if password and password_again and password != password_again:
            raise forms.ValidationError('sifre yanlis daxil edilib')
        elif User.objects.filter(password=password).exists():
            raise forms.ValidationError('bu sifre artiq istifade olunub')
        
class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput)

blog/views.py
from django.shortcuts import render,redirect
from .models import Blog,Contact,Author,Tag

# Create your views here.

def blog(request):
    author_username=request.GET.get('author')
    authors=Author.objects.all()
    blogs=Blog.objects.all()
    tags=Tag.objects.all()
    tag_title=request.GET.get('tag')
    if author_username:
       blogs=blogs.filter(author__user__username=author_username)
    if tag_title:
        blogs=blogs.filter(tags__title=tag_title)

    return render(request,'blog.html',context={'blogs':blogs,'tags':tags,'authors':authors})

def blog_detail(request,id):
    blog=Blog.objects.get(id=id)
    return render(request,'blog-detail.html',context={'blog':blog})

def contact(request):
    return render(request,'contact.html')

def contact_view(request):
    if request.method=='GET':
        return redirect('blog:contact')
    elif request.method=='POST':
        name=request.POST.get('name')
        phone=request.POST.get('phone')
        time=request.POST.get('time')
        email=request.POST.get('email')
        massage=request.POST.get('massage')
        date=request.POST.get('date')
        message=request.POST.get('message')
        contact=Contact(name=name,phone=phone,time=time,email=email,massage=massage,date=date,message=message)
        contact.save()
        return redirect('blog:contact')
    

info/views.py
from django.shortcuts import render
from .models import About
# Create your views here.

def home(request):
    return render(request,'home.html')

def about(request):
    abouts=About.objects.all()
    return render(request,'about.html',context={'abouts':abouts})

def service(request):
    return render(request,'service.html')

def about_view(request,id):
    about=About.objects.get(id=id)
    return render(request,'about-detail.html',context={'about':about})

user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib.auth import login,logout
from django.contrib.auth.models import User

# Create your views here.

def login_view(request):
    if request.method=='POST':
        form=LoginForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password')
            user=User.objects.filter(username=username).first()
            if user and user.check_password(password):
                login(request,user)
                return redirect('info:home')
            return render(request,'login.html',context={'form':form,'html_valid':True})
        return render(request,'login.html',context={'form':form})
    else:
        form=LoginForm()
        return render(request,'login.html',context={'form':form})
    

def register_view(request):
    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
            return redirect('info:home')
        return render(request,'register.html',context={'form':form})
    
    else:
        form=RegisterForm()
        return render(request,'register.html',context={'form':form})
    
def logout_view(request):
    logout(request)
    return redirect('user:login')

blog/templates/blog-detail.html
{% extends 'layout.html' %}
{% load static %}
{% block main %}
<article>
    <div class="container">

        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>{{blog.title}}</p>
                <h2>{{blog.description}}</h2>
                <h5 class="section">{{blog.content}}</h5>
                <a href="#">
                    <img class="img-responsive" width='600px' height='400px'  src= {{blog.image.url}}  alt="">
                </a>


                </div>
            </div>
        </div>
</article>

{% endblock main %}

blog/templates/blog.html
{% extends 'layout.html' %}
{% load static %}
      
         <!-- end header inner -->

      
      <!-- blog -->
   {% block main %}
      <div class="blog">
         <div class="container">

            <div class="row">
               <div class="col-md-12">
                  <div class="titlepage text_align_center ">
                     <h2>Latest Blog</h2>
                     <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu</p>
                  </div>
               </div>
            </div>
            <div class="row d-flex">
               {% for blog in blogs %}
               <div class=" col-4 ">
                  
                  <div class="latest">
                     <figure><img src={{blog.image.url}} alt="#"/></figure>
                     <span>{{blog.title}}</span>
                     <div class="nostrud">
                        <h3>{{blog.description}}</h3>
                        <p>{{blog.content}}</p>
                        {% with blog.author.user.username as author_username %}
                       <p class="post-meta">Posted by: <a href="?author={{ author_username }}">{{ blog.author.user.get_full_name }}</a></p>
                      
                       {% endwith %}
                     
                        <a class="read_more" href="{% url 'blog:blog-detail' id=blog.id %}">Read More</a>
                        
                     </div>
                  </div>
               </div>
               {% endfor %}
               {% for tag in tags %}
               <a href="?tag={{tag.title}}" class="badge ml-4 bg-secondary">{{tag.title}}</a>
           {% endfor %}
            </div>
         </div>
      </div>
   {% endblock main %}
      <!-- end blog -->
      <!--  footer -->
     

blog/templates/contact.html
{% extends 'layout.html' %}
{% load static %}
      <!-- end banner -->
      <!-- appointment -->
{% block main %}
      <div class="appointment">
         <div class="container">
            <div class="row">
               <div class="col-md-12 ">
                  <div class="titlepage text_align_center">
                     <h2>Contact Us</h2>
                     <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu</p>
                  </div>
               </div>
               <div class="col-md-12">
                  <form class="main_form" method="post" action="{% url 'blog:contact_view' %}">
                     {% csrf_token %}
                     <div class="row">
                        <div class="col-md-6 ">
                           <input class="form_control" placeholder="Your name" type="type" name="name" > 
                        </div>
                        <div class="col-md-6">
                           <input class="form_control" placeholder="Email" type="type" name="email"> 
                        </div>
                        <div class="col-md-6">
                           <input class="form_control" placeholder="Phone Number" type="type" name="phone">                          
                        </div>
                        <div class="col-md-6">
                           <input class="form_control" placeholder="Select Massage spa" type="type" name="massage">                          
                        </div>
                        <div class="col-md-6 ">
                           <input class="form_control" placeholder="Time" type="type" name="time"> 
                        </div>
                        <div class="col-md-6">
                           <input type="text" class="form_control"  placeholder="date" name="date" >
                        </div>
                        <div class="col-md-12">
                           <textarea style=" color: #d0d0cf;" class="textarea" placeholder="Message" type="type" name="message" >message </textarea>
                        </div>
                        <div class="col-md-12">
                           <button type="submit" class="send_btn">Send Now</button>
                        </div>
                     </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
      {% endblock main %}
      <!-- end appointment -->
      <!--  footer -->
     

info/templates/about-detail.html
{% extends 'layout.html' %}
{% load static %}
{% block main %}
<article>
    <div class="container">

        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>{{about.title}}</p>
                <h2>{{about.description}}</h2>
                <h5 class="section">{{about.content}}</h5>
                <a href="#">
                    <img class="img-responsive" width='600px' height='400px'  src= {{about.image.url}}  alt="">
                </a>


                </div>
            </div>
        </div>
</article>

{% endblock main %}

info/templates/about.html
{% extends 'layout.html' %}
{% load static %}
           
         <!-- end header inner -->
      
      <!-- end banner -->
      <!-- about -->
      {% block main %}
      <div class="about">
         <div class="container_width">
            <div class="row d_flex grig">
               {% for about in abouts %}
               <div class="col-md-6">
                  <div class="about_img">
                     <figure><img src={{about.image.url}} alt="#"/>
                     </figure>
                  </div>
               </div>
               {% endfor %}
               {% for about in abouts %}
               <div class="col-md-6 order">
                  <div class="titlepage text_align_left">
                     <h2>{{about.title}}</h2>
                     <p>{{about.description}}</p>
                     <a class="read_more" href="{% url 'info:about-detail' id=about.id %}">Read More</a>
                  </div>
               </div>
               {% endfor %}
            </div>
         </div>
      </div>
      {% endblock main %}
      <!-- end about -->
      <!--  footer -->
     

info/templates/service.html
{% extends 'layout.html' %}

{% load static %}
         <!-- end header inner -->
      
      <!-- end banner -->
      <!-- services -->
 {% block main %}
      <div class="services">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="titlepage text_align_center ">
                     <h2>Our Massage Services</h2>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-4">
                  <div id="ho_shad" class="services_box text_align_left">
                     <h3>Ayurveda Spa</h3>
                     <figure><img src="{% static 'images/service1.jpg' %}" alt="#"/></figure>
                     <p>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip</p>
                     <a class="read_more" href="service.html">Read More</a>
                  </div>
               </div>
               <div class="col-md-4">
                  <div id="ho_shad" class="services_box text_align_left">
                     <h3>Massage Spa</h3>
                     <figure><img src="{% static 'images/service2.jpg' %}" alt="#"/></figure>
                     <p>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip</p>
                     <a class="read_more" href="service.html">Read More</a>
                  </div>
               </div>
               <div class="col-md-4">
                  <div id="ho_shad" class="services_box text_align_left">
                     <h3>Luxury Spa</h3>
                     <figure><img src="{% static 'images/service3.jpg' %}" alt="#"/></figure>
                     <p>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip</p>
                     <a class="read_more" href="service.html">Read More</a>
                  </div>
               </div>
            </div>
         </div>
      </div>
      {% endblock main %}
      <!-- end services -->
      <!--  footer -->
     

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Bliss</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
   </head>
   <!-- body -->
   <body class="main-layout">
      <!-- loader  -->
      {% comment %} <div class="loader_bg">
         <div class="loader"><img src="{% static 'images/loading.gif' %}" alt="#"/></div>
      </div> {% endcomment %}
      <!-- end loader -->
      <div class="full_bg">
         <!-- header -->
         <header class="header-area">
            <div class="container">
               <div class="row d_flex">
                  <div class=" col-md-3 col-sm-3">
                     <div class="logo">
                        <a href="index.html">Bliss</a>
                     </div>
                  </div>
                  <div class="col-md-9 col-sm-9">
                     <div class="navbar-area">
                        <nav class="site-navbar">
                           <ul>
                              <li><a class="active" href="{% url 'info:home' %}">Home</a></li>
                              <li><a href="{% url 'info:about' %}">About</a></li>
                              <li><a href="{% url 'info:service' %}">Service</a></li>
                              <li><a href="{% url 'blog:blog' %}">Blog</a></li>
                              <li><a href="{% url 'blog:contact' %}">Contact us</a></li>
                              {% if request.user.is_authenticated %}
                              <li><a href="{% url 'user:logout' %}">Logout</a></li>
                              {% else %}
                              <li><a href="{% url 'user:login' %}">Login</a></li>
                              <li><a href="{% url 'user:register' %}">Register</a></li>
                              
                              {% endif %}
                            
                              <li class="d_none"><a href="Javascript:void(0)"><i class="fa fa-user" aria-hidden="true"></i></a></li>
                              <li class="d_none"><a href="Javascript:void(0)"><i class="fa fa-search" aria-hidden="true"></i></a></li>
                           </ul>
                           <button class="nav-toggler">
                           <span></span>
                           </button>
                        </nav>
                     </div>
                  </div>
               </div>
            </div>
         </header>

{% block main %}{% endblock main %}
         <footer>
            <div class="footer">
               <div class="container">
                  <div class="row">
                     <div class="col-md-7">
                        <div class="row">
                           <div class="col-lg-6 col-md-12">
                              <div class="hedingh3 text_align_left">
                                 <h3>About</h3>
                                 <p> Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable sourc</p>
                              </div>
                           </div>
                           <div class="col-lg-6 col-md-12">
                              <div class="hedingh3 text_align_left">
                                 <h3>Blog</h3>
                                 <p>Which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anythin</p>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-md-5">
                        <div class="row">
                           <div class="col-lg-6 col-md-12">
                              <div class="hedingh3 text_align_left">
                                 <h3>Menu</h3>
                                 <ul class="menu_footer">
                                    <li><a href="home.html">Home</a></li>
                                    <li><a href="index.html">About</a></li>
                                    <li><a href="service.html">Service</a></li>
                                    <li><a href="blog.html">Blog</a></li>
                                    <li><a href="contact.html">Contact us</a></li>
                                 </ul>
                              </div>
                           </div>
                           <div class="col-lg-6 col-md-12">
                              <div class="hedingh3  text_align_left">
                                 <h3>Newsletter</h3>
                                 <form id="colof" class="form_subscri">
                                    <input class="newsl" placeholder="Email" type="text" name="Email">
                                    <button class="subsci_btn">Subscribe</button>
                                 </form>
                                 <ul class="top_infomation">
                                    <li><i class="fa fa-phone" aria-hidden="true"></i>
                                       +01 1234567890
                                    </li>
                                    <li><i class="fa fa-envelope" aria-hidden="true"></i>
                                       <a href="Javascript:void(0)">demo@gmail.com</a>
                                    </li>
                                 </ul>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="copyright">
                  <div class="container">
                     <div class="row">
                        <div class="col-md-12">
                           <div class="follow text_align_center">
                              <h3>Follow Us</h3>
                              <ul class="social_icon ">
                                 <li><a href="Javascript:void(0)"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                 <li><a href="Javascript:void(0)"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                 <li><a href="Javascript:void(0)"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                                 <li><a href="Javascript:void(0)"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                              </ul>
                           </div>
                        </div>
                        <div class="col-md-12">
                           <p>© 2020 All Rights Reserved. Design by <a href="https://html.design/"> Free html Templates</a></p>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </footer>
         <!-- end footer -->
         <!-- Javascript files-->
         <script src="{% static 'js/jquery.min.js' %}"></script>
         <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
         <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
         <script src="{% static 'js/owl.carousel.min.js' %}"></script>
         <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
         <script src="{% static 'js/custom.js' %}"></script>
      </body>
   </html>

user/templates/login.html
{% extends 'layout.html' %}
{% load static %}
{%load crispy_forms_tags %} 
{% block main %}

<div class="container">
    <div class="row  mt-5">
        <div class="col-12 bg-warning p-3 text-center">
                <div>
                    <h2>LOGIN</h2>
                </div>
                {% if html_valid %}
                <h1 class="h4 text-danger">Username or password incorrect</h1>
                {% endif %}
                <form method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                    <input type="submit" class="btn btn-outline-danger">
            

        </div>
    </div>

</div>
{% endblock main %}

user/templates/register.html
{% extends 'layout.html' %}

{% load static %}
{%load crispy_forms_tags %} 
{% block main %}
<div class="container">
    <div class="row">
      <div class="col-lg-12 bg-warning text-center">
        <div>
          <h2>REGISTER</h2>
        </div>
        <form method="POST">
          {% csrf_token %}
          {{ form|crispy }}
          <input type="submit"class="btn btn-outline-danger">   
        </form>
      </div>
    </div>
  </div>
{% endblock main %}